export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className="flex justify-center items-center w-full min-h-screen bg-game bg-cover">
      <div className="flex justify-center items-center w-3/4 h-[1000px]">
        {children}
      </div>
    </div>
  );
}
